# Note: elements should be in lower case
#
# Rule types that drive HTML parser behavior
# INLINE inline element
# GROUP group element
# EXCLUDE exclude this element and all children
# INCLUDE exceptions to the exclude rules
# TEXTRUN make this element the delimeter of a run of inline elements that will be a single code
# TEXTMARKER tags must surround text in order for it to be translated
# TEXTUNIT make this element a textunit with skeleton before/after
# PRESERVE_WHITESPACE turn on preserve whitespace.
# SCRIPT Embedded scripting languatge - pass to another extractor
# SERVER Embedded server language tags such as JSP, PHP, Mason etc.
# ATTRIBUTE the rule lists an attribute, not an element
# ATTRIBUTES_ONLY only attribute is translatable or localizable 

#********************************************************************************************* 
# Operators for attribute value compare
#
# Rules are of the form:
# TO_EXTRACT_ATTRIBUTE:[IF_HAS_ATTRIBUTE, OPERATOR, VALUE]
# 'content':['http-equiv', EQUALS, 'keywords']
#
# This rule would read:
# extract the value of 'content' if the value of 'http-equiv' equals 'keywords'
#
# Multiple attribute values may be included in a list:
# 'content':['http-equiv', EQUALS, ['content-language', 'content-type']
#
# This rule would be read:
# extract the value of 'content' if the value of 'http-equiv' equals 'content-language' or 'content-type' 
#*******************************************************************************************/

# EQUALS
# NOT_EQUALS 
# MATCH regex match. Must match the entire attribute value

elements:
  filetype:
    ruleTypes: [ATTRIBUTES_ONLY]
    elementType: MSWORD
  
  'a:graphic':
    ruleTypes: [GROUP]

  'a:p':
    ruleTypes: [TEXTUNIT]
  
  'a:r':
    ruleTypes: [TEXTRUN]
  
  'a:t':
    ruleTypes: [TEXTMARKER]
  
  #'c:lang':
  #  ruleTypes: [ATTRIBUTES_ONLY]
  #  writableLocalizableAttributes: [val]
  
  'm:omathpara':
    ruleTypes: [EXCLUDE]

  'm:r':
    ruleTypes: [TEXTRUN]
  
  'm:t':
    ruleTypes: [TEXTMARKER]
  
  #'v:textbox':
  #  ruleTypes: [TEXTUNIT]
  #  elementType: textbox
  
  'v:textbox':
    ruleTypes: [GROUP]
  
  'v:textpath':
    ruleTypes: [ATTRIBUTES_ONLY]
    translatableAttributes: [string]

  'w:p':
    ruleTypes: [TEXTUNIT]
  
  'w:r':
    ruleTypes: [TEXTRUN]
  
  'pic:cnvpr':
    ruleTypes: [ATTRIBUTES_ONLY]
    translatableAttributes: [name]
    elementType: image
  
  'wp:docpr':
    ruleTypes: [ATTRIBUTES_ONLY]
    translatableAttributes: [name]

  'w:br':
    ruleTypes: [INLINE]
    elementType: br
  
  'w:del':
    ruleTypes: [INLINE]
    elementType: delete
  
  'w:ins':
    ruleTypes: [TEXTRUN]
    elementType: insert
  
  #'w:ppr':
  #  ruleTypes: [TEXTRUN]
  #  elementType: ParaStyle
  
  'w:lang':
    ruleTypes: [ATTRIBUTES_ONLY]
    writableLocalizableAttributes: ['w:val']
  
  'w:pstyle':
    ruleTypes: [INLINE]
    elementType: pstyle
  
  'w:rstyle':
    ruleTypes: [INLINE]
    elementType: rstyle
  
  'w:style':
    ruleTypes: [INLINE]
    elementType: style
  
  'w:t':
    ruleTypes: [TEXTMARKER]

  'w:tab':
    ruleTypes: [INLINE]
    elementType: tab
  
  'w:themefontlang':
    ruleTypes: [ATTRIBUTES_ONLY]
    writableLocalizableAttributes: ['w:val']
  
  'w:vanish':
    ruleTypes: [INLINE]
    elementType: hidden
    
  'wps:txbx':
    ruleTypes: [GROUP]
                          